name: context_extractor_ai
description: "ابزاری هوشمند برای استخراج زمینه کد پروژه برای استفاده در مدل‌های زبان بزرگ."
publish_to: 'none' 

version: 3.0.0+3

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  get: ^4.6.6
  file_picker: ^8.0.0+1
  shared_preferences: ^2.2.3
  path: ^1.9.0
  google_generative_ai: ^0.4.1
  flutter_dotenv: ^5.1.0
  flutter_spinkit: ^5.2.1
  clipboard: ^0.1.3
  iconsax: ^0.0.8
  google_fonts: ^6.2.1
  flutter_animate: ^4.5.0


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - .env
