name: context_extractor_ai
description: "ابزاری هوشمند برای استخراج زمینه کد پروژه برای استفاده در مدل‌های زبان بزرگ."
publish_to: 'none' 

version: 2.0.0+2

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # هسته اصلی مدیریت وضعیت و مسیریابی
  get: ^4.6.6

  # <<< جایگزینی: استفاده از پکیج رسمی فلاتر برای انتخاب فایل >>>
  # file_selector: ^1.0.3  <- دیگر مستقیما استفاده نمی‌شود، file_picker کامل‌تر است

  # <<< جدید: پکیج قدرتمند برای انتخاب فایل و پوشه >>>
  file_picker: ^8.0.0+1

  # <<< جدید: برای ذخیره‌سازی تاریخچه مسیرها >>>
  shared_preferences: ^2.2.3

  # <<< جدید: برای کار بهتر با مسیرهای فایل >>>
  path: ^1.9.0
  
  # برای ارتباط با Gemini API
  google_generative_ai: ^0.4.1
  
  # برای مدیریت امن کلید API جمنای
  flutter_dotenv: ^5.1.0

  # برای نمایش انیمیشن‌های لودینگ زیبا
  flutter_spinkit: ^5.2.1

  # برای کپی کردن متن خروجی در کلیپ‌بورد
  clipboard: ^0.1.3

  # برای زیباسازی UI
  iconsax: ^0.0.8
  google_fonts: ^6.2.1


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    # فایل .env برای نگهداری کلید API
    - .env

